name: Unit Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@2.30.2
        with:
          php-version: '8.2'

      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate App Key
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: ${{ github.sha }}

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          APP_KEY: ${{ steps.generate-uuid.outputs.uuid }}
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit -c phpunit.dist.xml
