name: Unit Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'

      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Generate App Key
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: ${{ github.sha }}

      - name: Execute PHPUnit tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          APP_KEY: ${{ steps.generate-uuid.outputs.uuid }}
        run: vendor/bin/phpunit -c phpunit.dist.xml
